/** Preview charger shown in the 3D yard before a real CP is commissioned. */
export const PREVIEW_CHARGER = {
  cpId: 'PREVIEW',
  connectionState: 'offline',
  bootAccepted: false,
  powerKw: 22,
  identity: {
    chargePointVendor: 'Massive Mobility',
    chargePointModel: 'Massive-CP-Sim-16',
    chargePointSerialNumber: 'MASSIVE-CPS-PREVIEW',
    firmwareVersion: 'Massive-CPS-16.3.2.1',
  },
  firmwareStatus: 'Idle',
  hardware: {
    chargeMode: 'AC',
    supply: 'AC grid → AC EVSE',
    cpuModel: 'ARM Cortex-A53 Quad @ 1.4 GHz',
    cpuPercent: 8,
    ramUsedMb: 280,
    ramTotalMb: 1024,
    romUsedMb: 1400,
    romTotalMb: 8192,
    tempC: 32,
    moduleTempC: 34,
    uptimeSec: 0,
    cooling: 'Forced-air',
  },
  energyRatePerKwh: 18.5,
  currency: 'INR',
  currencySymbol: '₹',
  authMode: 'local_or_csms',
  localAuthTags: ['CARD-7F2A91', 'FOB-ORBIT-44', 'TOKEN-MASSIVE-09'],
  connectors: [
    {
      number: 0,
      type: 'ChargePoint',
      name: 'Charge Point',
      status: 'Available',
      errorCode: 'NoError',
      powerKw: 22,
      cablePlugged: false,
      meterWh: 0,
      powerW: 0,
      sessionCost: 0,
    },
    {
      number: 1,
      type: 'Mennekes T2',
      name: 'Connector 1',
      status: 'Available',
      errorCode: 'NoError',
      powerKw: 22,
      cablePlugged: false,
      meterWh: 0,
      powerW: 0,
      sessionCost: 0,
      soc: null,
    },
    {
      number: 2,
      type: 'Mennekes T2',
      name: 'Connector 2',
      status: 'Available',
      errorCode: 'NoError',
      powerKw: 22,
      cablePlugged: false,
      meterWh: 0,
      powerW: 0,
      sessionCost: 0,
      soc: null,
    },
  ],
};
